# Сообщения при входе и выходе игроков
# Поддержка MiniMessage формата: https://docs.advntr.dev/minimessage/format.html
# Чтобы скрыть сообщение нужно указать "", например: quit-message: ""

# Формат отображения сообщений
# Доступные плейсхолдеры:
# %prefix% - префикс игрока из LuckPerms
# %player% - имя игрока
# %suffix% - суффикс игрока из LuckPerms
# %message% - основное сообщение (welcome-message, first-time-message, quit-message)
message-format: "%prefix%%player%%suffix% %message%"

# Основные сообщения
welcome-message: "<green>зашёл на сервер!"
first-time-message: "<green><bold>зашёл на сервер впервые!"
quit-message: "<red>вышел с сервера."

messages:
  no-permissions: "<red>У вас нет прав для этой команды!"
  config-reloaded: "<green>Конфиг WelcomeMessage перезагружен!"
  usage: "<yellow>Использование: /welcomemessage reload"
